export const FETCH_COURSE_DETAILS_REQUEST = "FETCH_COURSE_DETAILS_REQUEST";
export const FETCH_COURSE_DETAILS_SUCCESS = "FETCH_COURSE_DETAILS_SUCCESS";
export const FETCH_COURSE_DETAILS_FAILURE = "FETCH_COURSE_DETAILS_FAILURE";

export const ADD_COURSE_DETAIL_REQUEST = "ADD_COURSE_DETAIL_REQUEST";
export const ADD_COURSE_DETAIL_SUCCESS = "ADD_COURSE_DETAIL_SUCCESS";
export const ADD_COURSE_DETAIL_FAILURE = "ADD_COURSE_DETAIL_FAILURE";

export const UPDATE_COURSE_DETAIL_REQUEST = "UPDATE_COURSE_DETAIL_REQUEST";
export const UPDATE_COURSE_DETAIL_SUCCESS = "UPDATE_COURSE_DETAIL_SUCCESS";
export const UPDATE_COURSE_DETAIL_FAILURE = "UPDATE_COURSE_DETAIL_FAILURE";

export const DELETE_COURSE_DETAIL_REQUEST = "DELETE_COURSE_DETAIL_REQUEST";
export const DELETE_COURSE_DETAIL_SUCCESS = "DELETE_COURSE_DETAIL_SUCCESS";
export const DELETE_COURSE_DETAIL_FAILURE = "DELETE_COURSE_DETAIL_FAILURE";

export const UPDATE_COURSE_DETAIL_STATUS_REQUEST =
  "UPDATE_COURSE_DETAIL_STATUS_REQUEST";
export const UPDATE_COURSE_DETAIL_STATUS_SUCCESS =
  "UPDATE_COURSE_DETAIL_STATUS_SUCCESS";
export const UPDATE_COURSE_DETAIL_STATUS_FAILURE =
  "UPDATE_COURSE_DETAIL_STATUS_FAILURE";

export const SET_CURRENT_COURSE_DETAIL = "SET_CURRENT_COURSE_DETAIL";
export const CLEAR_CURRENT_COURSE_DETAIL = "CLEAR_CURRENT_COURSE_DETAIL";
