export const FETCH_SESSIONS_REQUEST = "FETCH_SESSIONS_REQUEST";
export const FETCH_SESSIONS_SUCCESS = "FETCH_SESSIONS_SUCCESS";
export const FETCH_SESSIONS_FAILURE = "FETCH_SESSIONS_FAILURE";

export const ADD_SESSION_REQUEST = "ADD_SESSION_REQUEST";
export const ADD_SESSION_SUCCESS = "ADD_SESSION_SUCCESS";
export const ADD_SESSION_FAILURE = "ADD_SESSION_FAILURE";

export const UPDATE_SESSION_REQUEST = "UPDATE_SESSION_REQUEST";
export const UPDATE_SESSION_SUCCESS = "UPDATE_SESSION_SUCCESS";
export const UPDATE_SESSION_FAILURE = "UPDATE_SESSION_FAILURE";

export const DELETE_SESSION_REQUEST = "DELETE_SESSION_REQUEST";
export const DELETE_SESSION_SUCCESS = "DELETE_SESSION_SUCCESS";
export const DELETE_SESSION_FAILURE = "DELETE_SESSION_FAILURE";

export const UPDATE_SESSION_STATUS_REQUEST = "UPDATE_SESSION_STATUS_REQUEST";
export const UPDATE_SESSION_STATUS_SUCCESS = "UPDATE_SESSION_STATUS_SUCCESS";
export const UPDATE_SESSION_STATUS_FAILURE = "UPDATE_SESSION_STATUS_FAILURE";

export const FETCH_SESSION_REQUEST = "FETCH_SESSION_REQUEST";
export const FETCH_SESSION_SUCCESS = "FETCH_SESSION_SUCCESS";
export const FETCH_SESSION_FAILURE = "FETCH_SESSION_FAILURE";
