export const FETCH_CUBE_SUBJECTS_REQUEST = "FETCH_CUBE_SUBJECTS_REQUEST";
export const FETCH_CUBE_SUBJECTS_SUCCESS = "FETCH_CUBE_SUBJECTS_SUCCESS";
export const FETCH_CUBE_SUBJECTS_FAILURE = "FETCH_CUBE_SUBJECTS_FAILURE";

export const ADD_CUBE_SUBJECT_REQUEST = "ADD_CUBE_SUBJECT_REQUEST";
export const ADD_CUBE_SUBJECT_SUCCESS = "ADD_CUBE_SUBJECT_SUCCESS";
export const ADD_CUBE_SUBJECT_FAILURE = "ADD_CUBE_SUBJECT_FAILURE";

export const UPDATE_CUBE_SUBJECT_REQUEST = "UPDATE_CUBE_SUBJECT_REQUEST";
export const UPDATE_CUBE_SUBJECT_SUCCESS = "UPDATE_CUBE_SUBJECT_SUCCESS";
export const UPDATE_CUBE_SUBJECT_FAILURE = "UPDATE_CUBE_SUBJECT_FAILURE";

export const DELETE_CUBE_SUBJECT_REQUEST = "DELETE_CUBE_SUBJECT_REQUEST";
export const DELETE_CUBE_SUBJECT_SUCCESS = "DELETE_CUBE_SUBJECT_SUCCESS";
export const DELETE_CUBE_SUBJECT_FAILURE = "DELETE_CUBE_SUBJECT_FAILURE";

export const UPDATE_CUBE_SUBJECT_STATUS_REQUEST = "UPDATE_CUBE_SUBJECT_STATUS_REQUEST";
export const UPDATE_CUBE_SUBJECT_STATUS_SUCCESS = "UPDATE_CUBE_SUBJECT_STATUS_SUCCESS";
export const UPDATE_CUBE_SUBJECT_STATUS_FAILURE = "UPDATE_CUBE_SUBJECT_STATUS_FAILURE";