export const FETCH_CUBE_SKILLS_REQUEST = "FETCH_CUBE_SKILLS_REQUEST";
export const FETCH_CUBE_SKILLS_SUCCESS = "FETCH_CUBE_SKILLS_SUCCESS";
export const FETCH_CUBE_SKILLS_FAILURE = "FETCH_CUBE_SKILLS_FAILURE";

export const ADD_CUBE_SKILL_REQUEST = "ADD_CUBE_SKILL_REQUEST";
export const ADD_CUBE_SKILL_SUCCESS = "ADD_CUBE_SKILL_SUCCESS";
export const ADD_CUBE_SKILL_FAILURE = "ADD_CUBE_SKILL_FAILURE";

export const UPDATE_CUBE_SKILL_REQUEST = "UPDATE_CUBE_SKILL_REQUEST";
export const UPDATE_CUBE_SKILL_SUCCESS = "UPDATE_CUBE_SKILL_SUCCESS";
export const UPDATE_CUBE_SKILL_FAILURE = "UPDATE_CUBE_SKILL_FAILURE";

export const DELETE_CUBE_SKILL_REQUEST = "DELETE_CUBE_SKILL_REQUEST";
export const DELETE_CUBE_SKILL_SUCCESS = "DELETE_CUBE_SKILL_SUCCESS";
export const DELETE_CUBE_SKILL_FAILURE = "DELETE_CUBE_SKILL_FAILURE";

export const UPDATE_CUBE_SKILL_STATUS_REQUEST = "UPDATE_CUBE_SKILL_STATUS_REQUEST";
export const UPDATE_CUBE_SKILL_STATUS_SUCCESS = "UPDATE_CUBE_SKILL_STATUS_SUCCESS";
export const UPDATE_CUBE_SKILL_STATUS_FAILURE = "UPDATE_CUBE_SKILL_STATUS_FAILURE";